"""Configuration types for retargeting task settings."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal


BoxScale = tuple[float, float, float]


@dataclass(frozen=True)
class TaskConfig:
    """Task-specific configuration parameters.

    These parameters control task-specific behavior like ground meshgrid generation,
    object sampling, augmentation, and scaling. Can be overridden via CLI.
    """

    # Object name
    # Auto-determined based on task_type if None: "largebox" for object_interaction,
    # "multi_boxes" for climbing, "ground" for robot_only
    object_name: str | None = None

    # Ground meshgrid (robot_only task)
    ground_size: int = 15
    ground_range: tuple[float, float] = (-1.0, 1.0)

    # Climbing ground meshgrid (climbing task)
    climbing_ground_size: int = 8
    climbing_ground_range: tuple[float, float] = (-2.0, 2.0)

    # Surface weight parameters for climbing object sampling (climbing task)
    # Used in weighted_surface_sampling: points with z-coordinate > threshold get high weight
    # This biases sampling toward top surfaces (important for climbing contact points)
    surface_weight_threshold: float = 0.9  # z-coordinate threshold for high-weight points
    surface_weight_high: int = 20  # Weight for top surface points (z > threshold)
    surface_weight_low: int = 1  # Weight for other points

    # Object directory (for climbing tasks)
    # Auto-determined from data_path / task_name if None
    object_dir: Path | None = None

    # Object-interaction geometry augmentation
    object_augmentation_mode: Literal["all", "pose", "scale", "mesh"] = "all"
    """Object-interaction variants generated by batch augmentation."""

    object_scale: BoxScale = (1.0, 1.0, 1.2)
    """Target box scale used by single-sequence ``--augmentation`` runs."""

    object_scale_variants: tuple[BoxScale, ...] = (
        (0.8, 0.8, 0.8),
        (1.2, 1.2, 1.2),
    )
    """Box scales added by batch object-interaction augmentation."""

    augmentation_object_mesh: Path | None = None
    """Optional target box OBJ used by a single-sequence augmentation run."""

    object_mesh_variants: tuple[Path, ...] = ()
    """Additional target box OBJ files added by batch augmentation.

    Variant meshes must describe boxes using the same local axes as the source
    object. Surface correspondences are transferred using their axis-aligned
    bounding boxes.
    """
